apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: grafana-headers
  namespace: monitoring
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Host: "grafana.local.ruizops.com"
